In [1]:
import pandas as pd
import numpy as np
import glob
import matplotlib.pyplot as plt
import matplotlib
matplotlib.style.use('ggplot')
import seaborn as sns
import seaborn.objects as so
from itertools import chain
import re
import glob
import os
pd.set_option("display.max_colwidth", None) 
pd.set_option("display.max_colwidth", None) 
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [ ]:
# /home/marlaux/miniconda3/envs/antismash/lib/python3.11/site-packages/antismash/detection/hmm_detection/data
# ./create_HMM_profile.sh Transposase-PF01610.fasta PF01610 Pfam
# echo -e "PF00266-Aminotransferase_classV_Cyano\tPF00266-Aminotransferase_classV_Cyano (NOT SxtA4)\t30\tPF00266-Aminotransferase_classV_Cyano.hmm" >> hmmdetails.txt

CondaError: Run 'conda init' before 'conda activate'


Note: you may need to restart the kernel to use updated packages.

### GET SEQUENCES FROM INTERPRO

In [31]:
!pwd

/home/marlaux/PAMPULHA/BGCs/FINAL/novas_regras_antismash/saxi_domains/interpro_full

## Run interproscan

In [ ]:
!/home/marlaux/interproscan-5.73-104.0/interproscan.sh -i FAAL-CD05931-cyano.fasta -appl CDD -cpu 20 -f TSV
!/home/marlaux/interproscan-5.73-104.0/interproscan.sh -i ATP-AMP-binding-PTHR22754-cyano.fasta -appl PANTHER -cpu 20 -f TSV
!/home/marlaux/interproscan-5.73-104.0/interproscan.sh -i AMP-dom_DIP2-like-PF23024-cyano.fasta -appl PFAM -cpu 20 -f TSV
!/home/marlaux/interproscan-5.73-104.0/interproscan.sh -i AcetylCoA_synthetase-SSF56801-cyano.fasta -appl SUPERFAMILY -cpu 20 -f TSV
!/home/marlaux/interproscan-5.73-104.0/interproscan.sh -i DUF4070-IPR025274-cyano.fasta -cpu 20 -f TSV

16/08/2024 11:23:49:212 Welcome to InterProScan-5.69-101.0
16/08/2024 11:23:49:212 Running InterProScan v5 in STANDALONE mode... on Linux
16/08/2024 11:23:52:381 RunID: CamaroAmarelo_20240816_112352268_e6a1
16/08/2024 11:23:58:041 Loading file /home/marlaux/PAMPULHA/BGCs/FINAL/saxi_domains/SxtA4-PF00155-Aminotran_1_2_Cyano.fasta
16/08/2024 11:23:58:041 Running the following analyses:
[AntiFam-7.0,CDD-3.20,Coils-2.2.1,FunFam-4.3.0,Gene3D-4.3.0,Hamap-2023_05,MobiDBLite-2.0,NCBIfam-15.0,PANTHER-18.0,Pfam-37.0,PIRSF-3.10,PIRSR-2023_05,PRINTS-42.0,ProSitePatterns-2023_05,ProSiteProfiles-2023_05,SFLD-4,SMART-9.0,SUPERFAMILY-1.75]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.
16/08/2024 11:26:19:677 95% completed
16/08/2024 11:29:19:667 100% done:  InterProScan analyses completed

In [24]:
domain = pd.read_csv('AcetylCoA_synthetase-SSF56801-cyano.fasta.tsv', sep="\t", header=None,
                       names= ["protein","sequence","seq_len","analysis","signature_acc","signature_desc","start","stop","score","status","date","interpro_acc","interpro_desc","GO_annotations","Pathways_annotations"])
domain_bed = domain[domain['signature_acc'] == 'SSF56801'][['protein','start','stop','signature_desc']].drop_duplicates()
domain_bed.head()

,protein,start,stop,signature_desc
1,A0A2T1GJK6|unreviewed|Carrier,188,748,Acetyl-CoA synthetase-like
3,A0A926VAA2|unreviewed|Acetyl-coenzyme,22,650,Acetyl-CoA synthetase-like
6,A0A9E4JLJ9|unreviewed|Carrier,502,1063,Acetyl-CoA synthetase-like
8,A0A6M8B8C6|unreviewed|AMP-dependent,6,467,Acetyl-CoA synthetase-like
9,H9N4H7|unreviewed|Carrier,3,204,Acetyl-CoA synthetase-like

In [13]:
domain = pd.read_csv('DUF4070-IPR025274-cyano.fasta.tsv', sep="\t", header=None,
                       names= ["protein","sequence","seq_len","analysis","signature_acc","signature_desc","start","stop","score","status","date","interpro_acc","interpro_desc","GO_annotations","Pathways_annotations"])
domain_bed = domain[domain['interpro_acc'] == 'IPR025274'][['protein','start','stop','interpro_desc']].drop_duplicates()
domain_bed.head()

,protein,start,stop,interpro_desc
9,A0A969UP35|unreviewed|Radical,340,482,Domain of unknown function DUF4070
13,T2IV47|unreviewed|Radical,339,482,Domain of unknown function DUF4070
26,G5IXZ5|unreviewed|Radical,339,482,Domain of unknown function DUF4070
48,A0AAW9PTI7|unreviewed|Radical,360,511,Domain of unknown function DUF4070
55,A0A3D4C1U4|unreviewed|Radical,359,501,Domain of unknown function DUF4070

In [ ]:
#Aminotran_cyano_bed = Aminotran[Aminotran['signature_acc'] == 'PF00155'][['protein','start','stop','signature_desc']].drop_duplicates()
#top_len = Aminotran_cyano.groupby(Aminotran_cyano['protein']).agg({'seq_len':'max'}).reset_index()
#Aminotran_cyano_len = pd.merge(top_len[['protein', 'seq_len']],
#                    Aminotran_cyano[['protein','seq_len','signature_acc','signature_desc','start','stop','score']], on=['protein', 'seq_len'], how='left').drop_duplicates()
#Aminotran_cyano_bed = Aminotran_cyano[['protein','start','stop','signature_desc']]
#Aminotran_pfam_bed.head()

7491

In [25]:
domain_bed.to_csv('AcetylCoA_synthetase-SSF56801-cyano-bed.tsv', sep='\t', index=False, header=False)

In [ ]:
!bedtools getfasta -fi AcetylCoA_synthetase-SSF56801-cyano.fasta -bed AcetylCoA_synthetase-SSF56801-cyano-bed.tsv > AcetylCoA_synthetase-SSF56801-cyano.faa

/bin/bash: line 1: bedtools: command not found

In [ ]:
!mafft --auto --clustalout --thread 20 AcetylCoA_synthetase-SSF56801-cyano.faa > AcetylCoA_synthetase-SSF56801-cyano.phy

In [ ]:
!hmmbuild AcetylCoA_synthetase-SSF56801-cyano.hmm AcetylCoA_synthetase-SSF56801-cyano.phy

In [2]:
cd saxi2

/home/marlaux/PAMPULHA/BGCs/FINAL/saxi_domains/saxi2

In [ ]:
!/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtA3-PF00550-PP_binding_Cyano.fasta -f TSV -appl Pfam -cpu 22
!/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtI-PF16861-Carbamoyltransferase-C-terminus.fasta -cpu 22
!/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtG-SSF55909-Pentein.fasta -f TSV -appl SUPERFAMILY -cpu 22
!/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtA2-SSF55729-Nat-Cyano.fasta -f TSV -appl SUPERFAMILY -cpu 22
!/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtB-PF00383-dCMP_cyt_deam_1.fasta -f TSV -appl Pfam -cpu 22
!/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtB-PF08211-dCMP_cyt_deam_2.fasta -f TSV -appl Pfam -cpu 22
!/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtA1-PF04055-Radical-SAM.fasta -f TSV -appl Pfam -cpu 22
!/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtHT-PF00355-Rieske.fasta -f TSV -appl Pfam -cpu 22
!/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtHT-PF19112-VanA_C.fasta -f TSV -appl Pfam -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtJ-PF19588.fasta -f TSV -appl Pfam -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtK-PF19451-DUF5989.fasta -f TSV -appl Pfam -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtW-PF12838-Fer4_7.fasta -f TSV -appl Pfam -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtW-PF13187-Fer4_9.fasta -f TSV -appl Pfam -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtV-PF00890-FAD_binding.fasta -f TSV -appl Pfam -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtV-PF02910-Succ_DH_flav_C.fasta -f TSV -appl Pfam -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtS-PF05721-phyH.fasta -f TSV -appl Pfam -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtU-PF00106-adh.fasta -f TSV -appl Pfam -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtD-PF04116-FA-hydroxylase.fasta -f TSV -appl Pfam -cpu 22
#####
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtN-PF19798-Sulfotransferase_5.fasta -f TSV -appl Pfam -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtX-PF04989-RMNT_CmcI.fasta -f TSV -appl Pfam -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtA3-SM00823-PKS_PP.fasta -f TSV -appl SMART -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtA2-PTHR43626-ACYL-COA-GNAT.fasta -f TSV -appl PANTHER -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtA4-PTHR13693-8-amino-7-oxononanoate.fasta -f TSV -appl PANTHER -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtG-PTHR10488-GLYCINE-AMIDINOTRANSFERASE.fasta -f TSV -appl PANTHER -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtHT-PTHR21266-IRON-SULFUR-DOMAIN.fasta -f TSV -appl PANTHER -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtI-PTHR34847-NodU-Carbamoyltransferase.fasta -f TSV -appl PANTHER -cpu 22

/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtA3-SSF47336-ACP-like.fasta -f TSV -appl SUPERFAMILY -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtB-SSF53927-Cytidine-deaminase-like.fasta -f TSV -appl SUPERFAMILY -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtL-SSF52266-SGNH-hydrolase.fasta -f TSV -appl SUPERFAMILY -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtS-SSF51197-Clavaminate-synthase-like.fasta -f TSV -appl SUPERFAMILY -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtA4-IPR015424-Pyridoxal_phosphate-dependent_transferase.fasta -f TSV -appl SUPERFAMILY -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtA4-SSF53383-PLP-dependent-transferases.fasta -f TSV -appl SUPERFAMILY -cpu 22

/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtHT-SSF50022-ISP-domain.fasta -f TSV -appl SUPERFAMILY -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtHT-SSF55961-Bet-v1-like.fasta -f TSV -appl SUPERFAMILY -cpu 22

/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtB-PTHR11644-Cytidine-Deaminase.fasta -f TSV -appl PANTHER -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtN-PTHR48331_Sulfotransferase_domain_containing.fasta -f TSV -appl PANTHER -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtU-PTHR43115-Short-chain-dehydrogenases.fasta -f TSV -appl PANTHER -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtV-PTHR11632-SUCCINATE-DEHYDROGENASE-FLAVOPROTEIN.fasta -f TSV -appl PANTHER -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtW-PTHR43687-Iron-Sulfur-Ferredoxin.fasta -f TSV -appl PANTHER -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtD-PTHR11863-Sterol-Desaturase.fasta -f TSV -appl PANTHER -cpu 22

/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtE-PF19454-DUF5992.fasta -f TSV -appl Pfam -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtFM-PF01554-MatE.fasta -f TSV -appl Pfam -cpu 22

/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtB-CD01283-cytidine_deaminase.fasta -f TSV -appl CDD -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtG-CD21136-L-arginine-glycine-amidinotransferase.fasta -f TSV -appl CDD -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtL-CD00229-SGNH_hydrolase.fasta -f TSV -appl CDD -cpu 22

/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtA4-PF00202-Aminotransferase_classIII.fasta -f TSV -appl Pfam -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtA4-PF00266-Aminotransferase_classV.fasta -f TSV -appl Pfam -cpu 22

/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtN-PF00685-Sulfotransferase_1.fasta -f TSV -appl Pfam -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtN-PF03567-Sulfotransferase_2.fasta -f TSV -appl Pfam -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtN-PF13469-Sulfotransferase_3.fasta -f TSV -appl Pfam -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtN-PF17784-Sulfotransferase_4.fasta -f TSV -appl Pfam -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtO-PF01583-Adenylylsulphate_kinase.fasta -f TSV -appl Pfam -cpu 22
/home/marlaux/interproscan-5.69-101.0/interproscan.sh -i SxtPER-PF00892-EamA-like-transporter.fasta -f TSV -appl Pfam -cpu 22

/home/marlaux/interproscan-5.73-104.0/interproscan.sh -i SxtPER-PTHR42920-Diverse-Substrate-Transporter.fasta -f TSV -appl PANTHER -cpu 22

/home/marlaux/interproscan-5.73-104.0/interproscan.sh -i SxtA2-G3DSA_3-40-630-30-Cyano.fasta -f TSV -cpu 20
/home/marlaux/interproscan-5.73-104.0/interproscan.sh -i SxtA2_GNAT-PS51186-Cyano.fasta -f TSV -cpu 20
/home/marlaux/interproscan-5.73-104.0/interproscan.sh -i SxtA1_SAM-SSF53335-Cyano.fasta -f TSV -cpu 20
/home/marlaux/interproscan-5.73-104.0/interproscan.sh -i SxtA3_CP_domain_PS50075-Cyano.fasta -f TSV -cpu 20
/home/marlaux/interproscan-5.73-104.0/interproscan.sh -i SxtA0-PF23525-AprA-MT2like-Cyano.fasta -f TSV -cpu 20
/home/marlaux/interproscan-5.73-104.0/interproscan.sh -i SxtA1-PF23525-Methyltransf_36-Cyano.fasta -f TSV -cpu 20
/home/marlaux/interproscan-5.73-104.0/interproscan.sh -i SxtG-G3DSA_3.75.10.10_Cyano.fasta -f TSV -cpu 20
/home/marlaux/interproscan-5.73-104.0/interproscan.sh -i AMP_binding-PF00501-cyano.fasta -f TSV -cpu 20


for file in ./*.fasta; do /home/marlaux/interproscan-5.73-104.0/interproscan.sh -i $file --cpu 20 -appl SUPERFAMILY,PANTHER,Gene3D,ProSiteProfiles,SMART,CDD,Pfam; done
/home/marlaux/interproscan-5.73-104.0/interproscan.sh -i AMP_binding-PF00501-cyano.fasta --cpu 20 -appl SUPERFAMILY,PANTHER,Gene3D,ProSiteProfiles,SMART,CDD,Pfam; done

16/08/2024 15:28:11:592 Welcome to InterProScan-5.69-101.0
16/08/2024 15:28:11:592 Running InterProScan v5 in STANDALONE mode... on Linux
16/08/2024 15:28:14:491 RunID: CamaroAmarelo_20240816_152814401_7jud
^C
16/08/2024 15:28:20:063 Welcome to InterProScan-5.69-101.0
16/08/2024 15:28:20:063 Running InterProScan v5 in STANDALONE mode... on Linux
16/08/2024 15:28:22:908 RunID: CamaroAmarelo_20240816_152822821_c6zv
16/08/2024 15:28:28:749 Loading file /home/marlaux/PAMPULHA/BGCs/FINAL/saxi_domains/SxtI-PF16861-Carbamoyltransferase-C-terminus.fasta
16/08/2024 15:28:28:750 Running the following analyses:
[AntiFam-7.0,CDD-3.20,Coils-2.2.1,FunFam-4.3.0,Gene3D-4.3.0,Hamap-2023_05,MobiDBLite-2.0,NCBIfam-15.0,PANTHER-18.0,Pfam-37.0,PIRSF-3.10,PIRSR-2023_05,PRINTS-42.0,ProSitePatterns-2023_05,ProSiteProfiles-2023_05,SFLD-4,SMART-9.0,SUPERFAMILY-1.75]
Available matches will be retrieved from the pre-calculated match lookup service.

Matches for any sequences that are not represented in the lookup service will be calculated locally.

In [3]:
cd saxi2

/home/marlaux/PAMPULHA/BGCs/FINAL/saxi_domains/saxi2

In [25]:
interproscan = pd.read_csv('SxtG-G3DSA_3.75.10.10_Cyano.fasta.tsv', sep="\t", header=None,
                       names= ["protein","sequence","seq_len","analysis","signature_acc","signature_desc","start","stop","score","status","date","interpro_acc","interpro_desc","GO_annotations","Pathways_annotations"])
#interproscan[interproscan['signature_acc'].str.contains('PS51186', na=False)][['signature_acc','protein','start','stop','signature_desc']].drop_duplicates().head()
#interproscan[interproscan['signature_acc'] == 'PS50075'][['signature_acc','protein','start','stop','signature_desc']].drop_duplicates().head()
#interproscan_bed = interproscan[interproscan['signature_acc'] == 'PF23525'][['protein','start','stop','signature_desc']].drop_duplicates()
interproscan_bed = interproscan[interproscan['signature_acc'].str.contains('G3DSA:3.75.10.10', na=False)][['protein','start','stop','signature_desc']].drop_duplicates()
interproscan_bed.to_csv('SxtG-G3DSA_3.75.10.10_Cyano_bed.tsv', sep='\t', index=False, header=False)
#interproscan_bed.head()

In [ ]:
bedtools getfasta -fi SxtG-G3DSA_3.75.10.10_Cyano.fasta -bed SxtG-G3DSA_3.75.10.10_Cyano_bed.tsv > SxtG-G3DSA_3.75.10.10_Cyano.faa

mafft --auto --clustalout --thread 20 SxtG-G3DSA_3.75.10.10_Cyano.faa > SxtG-G3DSA_3.75.10.10_Cyano.phy

hmmbuild SxtG-G3DSA_3.75.10.10_Cyano.hmm SxtG-G3DSA_3.75.10.10_Cyano.phy

SyntaxError: invalid syntax (3182791401.py, line 1)

In [ ]:
/home/marlaux/anaconda3/envs/antismash/lib/python3.10/site-packages/antismash/detection/hmm_detection/data

In [ ]:
INTERPRO
>>> /home/marlaux/PAMPULHA/interpro/find_SXT/PlanktoPAMP --> Raphi + Plankto
>>> /home/marlaux/PAMPULHA/interpro/find_SXT/refs_interpro

In [28]:
SxtG_G3DSA_interproscan = pd.read_csv('SxtG-G3DSA_3.75.10.10_Cyano.fasta.tsv', sep="\t", header=None,
                       names= ["protein","sequence","seq_len","analysis","signature_acc","signature_desc","start","stop","score","status","date","interpro_acc","interpro_desc","GO_annotations","Pathways_annotations"])
SxtG_G3DSA_interproscan = SxtG_G3DSA_interproscan[SxtG_G3DSA_interproscan['score'] != '-']
SxtG_G3DSA_interproscan['score'] = SxtG_G3DSA_interproscan['score'].astype(float)
threshold = 0.05

In [30]:
SxtG_G3DSA_interproscan.head()
SxtG_G3DSA_interproscan[(SxtG_G3DSA_interproscan['score'] < threshold)] \
    [['protein','start','stop','score','analysis','signature_acc','signature_desc','interpro_acc','interpro_desc']].sort_values(by='start', ascending=True).head()

,protein,start,stop,score,analysis,signature_acc,signature_desc,interpro_acc,interpro_desc
1901,A0A6P0VPY6|unreviewed|Amidinotransferase|taxID:2607766,1,334,5.400000e-86,Gene3D,G3DSA:3.75.10.10,-,-,-
3945,A0A7W2A376|unreviewed|Glycine,1,388,9.990000e-83,SUPERFAMILY,SSF55909,Pentein,-,-
6199,G1DTC4|unreviewed|CyrA|taxID:940192,1,158,1.200000e-44,Gene3D,G3DSA:3.75.10.10,-,-,-
6225,A0A916R1X8|unreviewed|Amidinotransferase|taxID:2720165,1,215,6.000000e-38,Gene3D,G3DSA:3.75.10.10,-,-,-
502,L8LVP3|unreviewed|Arginine,1,422,0.000000e+00,PIRSF,PIRSF006356,ADI,IPR003876,Arginine deiminase

In [38]:
SxtG_G3DSA_interproscan = pd.read_csv('SxtG-G3DSA_3.75.10.10_Cyano.fasta.tsv', sep="\t", header=None,
                       names= ["protein","sequence","seq_len","analysis","signature_acc","signature_desc","start","stop","score","status","date","interpro_acc","interpro_desc","GO_annotations","Pathways_annotations"])
SxtG_G3DSA_interproscan = SxtG_G3DSA_interproscan[SxtG_G3DSA_interproscan['score'] != '-']
SxtG_G3DSA_interproscan['score'] = SxtG_G3DSA_interproscan['score'].astype(float)
sample_identifier = 'SxtG_G3DSA'
SxtG_G3DSA_interproscan = SxtG_G3DSA_interproscan[(SxtG_G3DSA_interproscan['score'] < threshold)] \
    [['analysis','signature_acc','signature_desc','interpro_acc','interpro_desc']].drop_duplicates().reset_index(drop=True)
SxtG_G3DSA_interproscan['Sxt_domain'] = sample_identifier
SxtG_G3DSA_interproscan.head()

,analysis,signature_acc,signature_desc,interpro_acc,interpro_desc,Sxt_domain
0,PANTHER,PTHR31377,AGMATINE DEIMINASE-RELATED,IPR007466,"Peptidyl-arginine deiminase, Porphyromonas-type",SxtG_G3DSA
1,Gene3D,G3DSA:3.75.10.10,-,-,-,SxtG_G3DSA
2,SUPERFAMILY,SSF55909,Pentein,-,-,SxtG_G3DSA
3,Pfam,PF04371,Porphyromonas-type peptidyl-arginine deiminase,IPR007466,"Peptidyl-arginine deiminase, Porphyromonas-type",SxtG_G3DSA
4,Pfam,PF21570,"Arginine dihydrolase ArgZ-like, C-terminal, Rossmann fold",IPR048963,"Arginine dihydrolase ArgZ/ArgE-like, C-terminal, second subdomain",SxtG_G3DSA

In [50]:
SxtG_Pentein_interproscan = pd.read_csv('SxtG-SSF55909-Pentein.fasta.tsv', sep="\t", header=None,
                       names= ["protein","sequence","seq_len","analysis","signature_acc","signature_desc","start","stop","score","status","date","interpro_acc","interpro_desc","GO_annotations","Pathways_annotations"])
SxtG_Pentein_interproscan = SxtG_Pentein_interproscan[SxtG_Pentein_interproscan['score'] != '-']
SxtG_Pentein_interproscan['score'] = SxtG_Pentein_interproscan['score'].astype(float)
sample_identifier = 'SxtG_Pentein'
SxtG_Pentein_interproscan = SxtG_Pentein_interproscan[(SxtG_Pentein_interproscan['score'] < threshold)] \
    [['analysis','signature_acc','signature_desc','interpro_acc','interpro_desc']].drop_duplicates().reset_index(drop=True)
SxtG_Pentein_interproscan['Sxt_domain'] = sample_identifier
SxtG_Pentein_interproscan

,analysis,signature_acc,signature_desc,interpro_acc,interpro_desc,Sxt_domain
0,SUPERFAMILY,SSF55909,Pentein,-,-,SxtG_Pentein
1,SUPERFAMILY,SSF52467,DHS-like NAD/FAD-binding domain,IPR029035,DHS-like NAD/FAD-binding domain superfamily,SxtG_Pentein
2,SUPERFAMILY,SSF110083,"Peptidylarginine deiminase Pad4, middle domain",IPR036556,"Protein-arginine deiminase, central domain superfamily",SxtG_Pentein
3,SUPERFAMILY,SSF56801,Acetyl-CoA synthetase-like,-,-,SxtG_Pentein
4,SUPERFAMILY,SSF47336,ACP-like,IPR036736,ACP-like superfamily,SxtG_Pentein
5,SUPERFAMILY,SSF52172,CheY-like,IPR011006,CheY-like superfamily,SxtG_Pentein

In [53]:
SxtA2_Gcn5_interproscan = pd.read_csv('SxtA2_GNAT-PS51186-Cyano.fasta.tsv', sep="\t", header=None,
                       names= ["protein","sequence","seq_len","analysis","signature_acc","signature_desc","start","stop","score","status","date","interpro_acc","interpro_desc","GO_annotations","Pathways_annotations"])
SxtA2_Gcn5_interproscan = SxtA2_Gcn5_interproscan[SxtA2_Gcn5_interproscan['score'] != '-']
SxtA2_Gcn5_interproscan['score'] = SxtA2_Gcn5_interproscan['score'].astype(float)
sample_identifier = 'SxtA2'
SxtA2_Gcn5_interproscan = SxtA2_Gcn5_interproscan[(SxtA2_Gcn5_interproscan['score'] < threshold)] \
    [['analysis','signature_acc','signature_desc','interpro_acc','interpro_desc']].drop_duplicates().reset_index(drop=True)
SxtA2_Gcn5_interproscan['Sxt_domain'] = sample_identifier
SxtA2_Gcn5_interproscan.head()

,analysis,signature_acc,signature_desc,interpro_acc,interpro_desc,Sxt_domain
0,FunFam,G3DSA:3.40.630.30:FF:000064,GNAT family acetyltransferase,-,-,SxtA2
1,Pfam,PF00583,Acetyltransferase (GNAT) family,IPR000182,GNAT domain,SxtA2
2,CDD,cd04301,NAT_SF,-,-,SxtA2
3,PANTHER,PTHR10545,DIAMINE N-ACETYLTRANSFERASE,IPR051016,Diverse Substrate Acetyltransferase,SxtA2
4,SUPERFAMILY,SSF55729,Acyl-CoA N-acyltransferases (Nat),IPR016181,Acyl-CoA N-acyltransferase,SxtA2

In [ ]:
#cd interpro_full
%cd ..

/home/marlaux/PAMPULHA/BGCs/FINAL/novas_regras_antismash/saxi_domains

In [42]:
import pandas as pd
import glob

# Define the threshold
threshold = 0.05

# List of files to process
files = glob.glob('*.tsv')

# Initialize an empty list to store DataFrames
dataframes = []

# Loop through each file
for file in files:
    # Read the file into a DataFrame
    df = pd.read_csv(file, sep="\t", header=None,
                     names=["protein", "sequence", "seq_len", "analysis", "signature_acc", "signature_desc", "start", "stop", "score", "status", "date", "interpro_acc", "interpro_desc", "GO_annotations", "Pathways_annotations"])
    
    # Filter out rows where 'score' is '-'
    df = df[df['score'] != '-']
    
    # Convert 'score' to float
    df['score'] = df['score'].astype(float)
    
    # Filter rows based on the threshold
    df = df[df['score'] < threshold]
    
    # Select specific columns and drop duplicates
    df = df[['analysis', 'signature_acc', 'signature_desc', 'interpro_acc', 'interpro_desc']].drop_duplicates().reset_index(drop=True)
    
    # Add a column with the filename as the sample identifier
    df['sample_identifier'] = file
    
    # Append the DataFrame to the list
    dataframes.append(df)

# Concatenate all DataFrames into a single DataFrame
interpro_domains_full = pd.concat(dataframes, ignore_index=True)

# Display the result
#print(result_df)
interpro_domains_full.head()

,analysis,signature_acc,signature_desc,interpro_acc,interpro_desc,sample_identifier
0,SUPERFAMILY,SSF53383,PLP-dependent transferases,IPR015424,Pyridoxal phosphate-dependent transferase,SxtA4-IPR015424-Pyridoxal_phosphate-dependent_transferase.fasta.tsv
1,SUPERFAMILY,SSF52821,Rhodanese/Cell cycle control phosphatase,IPR036873,Rhodanese-like domain superfamily,SxtA4-IPR015424-Pyridoxal_phosphate-dependent_transferase.fasta.tsv
2,SUPERFAMILY,SSF55904,Ornithine decarboxylase C-terminal domain,IPR036633,"Orn/Lys/Arg decarboxylase, C-terminal domain superfamily",SxtA4-IPR015424-Pyridoxal_phosphate-dependent_transferase.fasta.tsv
3,SUPERFAMILY,SSF46785,Winged helix DNA-binding domain,IPR036390,Winged helix DNA-binding domain superfamily,SxtA4-IPR015424-Pyridoxal_phosphate-dependent_transferase.fasta.tsv
4,SUPERFAMILY,SSF52777,CoA-dependent acyltransferases,-,-,SxtA4-IPR015424-Pyridoxal_phosphate-dependent_transferase.fasta.tsv

In [45]:
# SxtA3-SSF47336-ACP-like.fasta.tsv and SxtA4-SSF53383-PLP-dependent out --> too big
interpro_domains_full[interpro_domains_full['signature_acc'].str.contains('PF02310', na=False)].sort_values(by='sample_identifier', ascending=True)

,analysis,signature_acc,signature_desc,interpro_acc,interpro_desc,sample_identifier
2207,Pfam,PF02310,B12 binding domain,IPR006158,Cobalamin (vitamin B12)-binding domain,PF02310_B12_binding_cyano.fasta.tsv
139,Pfam,PF02310,B12 binding domain,IPR006158,Cobalamin (vitamin B12)-binding domain,SxtA1-PF04055-Radical-SAM.fasta.tsv

In [48]:
interpro_domains_full[interpro_domains_full['interpro_acc'].str.contains('IPR050307', na=False)]
interpro_domains_full[interpro_domains_full['signature_acc'].str.contains('SSF56801', na=False)].sort_values(by='sample_identifier', ascending=True)

,analysis,signature_acc,signature_desc,interpro_acc,interpro_desc,sample_identifier
2602,SUPERFAMILY,SSF56801,Acetyl-CoA synthetase-like,-,-,SxtA1-PF23525-Methyltransf_36-Cyano_interpro_full.tsv
550,SUPERFAMILY,SSF56801,Acetyl-CoA synthetase-like,-,-,SxtA2-G3DSA_3-40-630-30-Cyano_interpro_full.tsv
884,SUPERFAMILY,SSF56801,Acetyl-CoA synthetase-like,-,-,SxtA2-SSF55729-Nat-Cyano.fasta.tsv
1963,SUPERFAMILY,SSF56801,Acetyl-CoA synthetase-like,-,-,SxtA2-SSF55729-Nat-Cyano_interpro_full.tsv
2946,SUPERFAMILY,SSF56801,Acetyl-CoA synthetase-like,-,-,SxtA2_GNAT-PS51186-Cyano_interpro_full.tsv
2481,SUPERFAMILY,SSF56801,Acetyl-CoA synthetase-like,-,-,SxtA3-SSF47336-ACP-like.fasta.tsv
11,SUPERFAMILY,SSF56801,Acetyl-CoA synthetase-like,-,-,SxtA4-IPR015424-Pyridoxal_phosphate-dependent_transferase.fasta.tsv
961,SUPERFAMILY,SSF56801,Acetyl-CoA synthetase-like,-,-,SxtA4-IPR015424-Pyridoxal_phosphate-dependent_transferase_interpro_full.tsv
3496,SUPERFAMILY,SSF56801,Acetyl-CoA synthetase-like,-,-,SxtA4-PF00155-Aminotran_1_2_Cyano_interpro_full.tsv
3576,SUPERFAMILY,SSF56801,Acetyl-CoA synthetase-like,-,-,SxtA4-SSF53383-PLP-dependent-transferases.fasta.tsv
3095,SUPERFAMILY,SSF56801,Acetyl-CoA synthetase-like,-,-,SxtB-SSF53927-Cytidine-deaminase-like.fasta.tsv
2396,SUPERFAMILY,SSF56801,Acetyl-CoA synthetase-like,-,-,SxtB-SSF53927-Cytidine-deaminase-like_interpro_full.tsv
1073,SUPERFAMILY,SSF56801,Acetyl-CoA synthetase-like,-,-,SxtG-CD21136-L-arginine-glycine-amidinotransferase_interpro_full.tsv
2454,SUPERFAMILY,SSF56801,Acetyl-CoA synthetase-like,-,-,SxtG-G3DSA_3.75.10.10_Cyano_interpro_full.tsv
910,SUPERFAMILY,SSF56801,Acetyl-CoA synthetase-like,-,-,SxtG-SSF55909-Pentein.fasta.tsv
1393,SUPERFAMILY,SSF56801,Acetyl-CoA synthetase-like,-,-,SxtG-SSF55909-Pentein_interpro_full.tsv
2256,SUPERFAMILY,SSF56801,Acetyl-CoA synthetase-like,-,-,SxtL-SSF52266-SGNH-hydrolase.fasta.tsv
3188,SUPERFAMILY,SSF56801,Acetyl-CoA synthetase-like,-,-,SxtS-SSF51197-Clavaminate-synthase-like.fasta.tsv

In [63]:
interpro_domains_full[interpro_domains_full['signature_acc'].str.contains('PF00501', na=False)].sort_values(by='sample_identifier', ascending=True)
interpro_domains_full[interpro_domains_full['signature_acc'].str.contains('PF05118', na=False)].sort_values(by='sample_identifier', ascending=True)
interpro_domains_full[interpro_domains_full['signature_acc'].str.contains('SSF51197', na=False)].sort_values(by='sample_identifier', ascending=True)
interpro_domains_full[interpro_domains_full['signature_acc'].str.contains('PF13439', na=False)].sort_values(by='sample_identifier', ascending=True)
interpro_domains_full[interpro_domains_full['signature_acc'].str.contains('PF00534', na=False)].sort_values(by='sample_identifier', ascending=True)
interpro_domains_full[interpro_domains_full['signature_acc'].str.contains('SSF52540', na=False)].sort_values(by='sample_identifier', ascending=True)
interpro_domains_full[interpro_domains_full['signature_acc'].str.contains('SSF53850', na=False)].sort_values(by='sample_identifier', ascending=True)
interpro_domains_full[interpro_domains_full['signature_acc'].str.contains('cd13590', na=False)].sort_values(by='sample_identifier', ascending=True)

Empty DataFrame
Columns: [analysis, signature_acc, signature_desc, interpro_acc, interpro_desc, sample_identifier]
Index: []

get BLAST aligned query sequences (qseq):

In [ ]:
!for file in ./*_BH_bitscore.tab; do echo $file; base="$(basename $file _BH_bitscore.tab)";    \
                awk -F '\t' 'NR>1 {print ">"$1"|"$3"\n"$13}' $file > ${base}_BH_bitscore_qseq2.faa; done

In [ ]:
!for file in ./*_BH_sim.tab; do echo $file; base="$(basename $file _BH_sim.tab)";    \
                awk -F '\t' 'NR>1 {print ">"$1"|"$3"\n"$13}' $file > ${base}_BH_sim_qseq.faa; done

In [ ]:
!head PS14_AG13bin4_sxt_prot_NCBI_blastx_BH_bitscore_qseq.faa

In [ ]:
!head PS14_AG13bin4_sxt_prot_NCBI_blastx_BH_sim_qseq.faa

Verificar os top hits de Sxt:

In [ ]:
!head PS22_AG15bin8_sxt_prot_NCBI_blastx_BH_sim.tab

In [ ]:
!for file in *_sxt_prot_NCBI_blastx_BH_sim.tab; do echo $file; grep -i "Sxt" $file | cut -f 1,2,8,10,11,12 | sort -k2 -nr | head; done

In [ ]:
!grep -E 'SxtA|polyketide synthase' PS20_AG14bin11_sxt_prot_NCBI_blastx_seq.tab | grep -v "SxtJ" | sort -k8 -nr | head

In [ ]:
!for file in ./*_sxt_prot_NCBI_blastx_seq.tab; do echo $file; base="$(basename $file _sxt_prot_NCBI_blastx_seq.tab)";   
        grep -E 'SxtA|polyketide synthase' $file > ${base}_SxtA_NCBI_blastx_seq.tab; done

In [ ]:
!for file in ./*_SxtA_NCBI_blastx_seq.tab; do echo $file; base="$(basename $file _SxtA_NCBI_blastx_seq.tab)"; awk -F '\t' 'NR>0 {print ">"$1"|"$3"-"$4"|"$2" "$12"\n"$13}' $file > ${base}_SxtA_NCBI_blastx_qseq.faa; done

In [ ]:
!for file in *_SxtA_NCBI_blastx_seq.tab; do python3 parse_blast_output_simple.py $file; done

In [ ]:
!for file in *.tmp; do python3 parse_bed.py $file; done

In [ ]:
!for file in ../*.fasta; do echo $file; base="$(basename $file .fasta)"; bedtools getfasta -fi $file -bed ${base}_SxtA_NCBI_blastx_qbed.bed > ${base}_SxtA_NCBI_blastx_qbed_genomic.fas; done

In [ ]:
!for file in ./*_SxtA_NCBI_blastx_qbed_genomic.fas; do echo $file; base="$(basename $file _SxtA_NCBI_blastx_qbed_genomic.fas)"; 
        blastn -task 'dc-megablast' -query $file -db ../refs_genomic/SXT_T3_toxin_cluster_annotations_genomic3.fasta -num_threads 16 -parse_deflines -outfmt 11 -out ${base}_SxtA_NCBI_blastx_genomic_T3_dcmegablast.out; done

In [ ]:
!for file in ./*_SxtA_NCBI_blastx_genomic_T3_dcmegablast.out; do echo $file; base="$(basename $file _SxtA_NCBI_blastx_genomic_refsNCBInucl_dcmegablast.out)";    \
                blast_formatter -archive $file  \
                -outfmt "6 qseqid sseqid qstart qend sstart send length pident qcovhsp evalue bitscore stitle qseq sseq"    \
                -out ${base}_SxtA_NCBI_blastx_genomic_T3_dcmegablast_seq.tab; done

Não pegou nada

**2. map the extracted genomic sequences against the Planktothrix protein NCBI database**

*2.a Download Planktothrix genome package:"

In [ ]:
!./NCBI_download_refs.sh -h

In [ ]:
!./NCBI_download_refs.sh -n Planktothrix -t txid54304 -p Planktothrix

In [ ]:
!ls -t | head

*2.b rename protein files from the genome references with the respective accession:*

In [ ]:
!python3 NCBI_protein_rename.py Planktothrix_genome_package/data

In [ ]:
!ls Planktothrix_genome_package/data | head

*2.c concatenate the protein sequences from all references, remove duplicates, and build the database:*

In [ ]:
!cat Planktothrix_genome_package/data/*.faa > Planktothrix_genome_package/Planktothrix_refs_protein.faa

In [ ]:
!seqkit rmdup -s < Planktothrix_genome_package/Planktothrix_refs_protein.faa > Planktothrix_genome_package/Planktothrix_refs_protein_clean.faa

In [ ]:
!ls Planktothrix_genome_package/
!head Planktothrix_genome_package/Planktothrix_refs_protein_clean.faa

*2.d Build blast reference database*

In [ ]:
!makeblastdb -in Planktothrix_genome_package/Planktothrix_refs_protein_clean.faa -dbtype prot -parse_seqids

*2.e run blastx saxitoxin hit genomic sequences against Planktothrix NCBI protein database:*<p>
Use similarity besthit first:

In [ ]:
!for file in ./*_genomic_edit.fas; do echo $file; base="$(basename $file _genomic_edit.fasta)";    \
                blastx -query $file \
                -db Planktothrix_genome_package/Planktothrix_refs_protein_clean.faa \
                -num_threads 16 \
                -parse_deflines \
                -outfmt 11       \
                -out ${base}_genomic_blastx.out; done

*2.f convert blast output to tab, with selected columns and the aligned sequences (qseq and sseq)*

In [ ]:
!for file in ./*_BH_sim_NCBI_refs_blastx.out; do echo $file; base="$(basename $file _BH_sim_NCBI_refs_blastx.out)";    \
                blast_formatter -archive $file  \
                -outfmt "6 qseqid sseqid qstart qend sstart send length pident qcovhsp evalue bitscore stitle qseq sseq"    \
                -out ${base}_BH_sim_NCBI_refs_blastx_seq.tab; done

In [ ]:
!head PS20_AG14bin11_sxt_prot_NCBI_blastx_BH_sim_NCBI_refs_blastx_seq.tab

*3. functional annotation with eggNOG-mapper:*

In [ ]:
!mkdir eggNOG_diamond_BH_sim

In [ ]:
!emapper.py -h

In [ ]:
!for file in *_BH_sim_genomic_edit.fasta; do echo $file; base="$(basename $file _besthit_genomic.edit.fasta)";    \
                emapper.py --cpu 16 -m diamond --itype genome -i $file --genepred prodigal -o ${base}_BH_sim_eggnog --output_dir ./eggNOG_diamond_BH_sim  \
                --report_orthologs --decorate_gff yes; done